arch:
    - amd64
    - arm64
conan-linux: &conan-linux
  os: linux
  dist: xenial
  language: python
  python: "3.8"
  services:
    - docker
  install:
    - ./conan/travis/install.sh
  script:
    - ./conan/travis/build.sh
  if: tag IS present

conan-linux-master: &conan-linux-master
  os: linux
  dist: xenial
  language: python
  python: "3.8"
  services:
    - docker
  install:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./conan/travis/install.sh; fi'
  script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./conan/travis/build.sh; fi'
  branches:
    only:
    - master


    - language: generic
      os: linux
      install:
        - bash .travis/format_install.sh
        
      script:
        - bash .travis/format_check.sh
